kind: pipeline
type: exec
name: web server

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: updating web nuxt application
  commands:
  - cd /home/atera/atera_web_architecture/drone_exec/
  - ./update_atera_nuxt.sh

trigger:
  branch:
  - release
  event:
  - push